//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmitriev_PZ2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Report_ID { get; set; }
        public int PoliceLeadership_ID { get; set; }
        public string Text { get; set; }
    
        public virtual PoliceLeadership PoliceLeadership { get; set; }
    }
}
