//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmitriev_PZ2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_ID { get; set; }
        public int UserRole_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
